const NOTIFICATION_TYPES = Object.freeze({
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_ACCEPTED: "BOOKING_ACCEPTED",
  BOOKING_DECLINED: "BOOKING_DECLINED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
  BOOKING_REMINDER: "BOOKING_REMINDER",

  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",

  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  REFUND_PROCESSED: "REFUND_PROCESSED",

  SUBSCRIPTION_TRIAL_STARTED: "SUBSCRIPTION_TRIAL_STARTED",
  SUBSCRIPTION_TRIAL_ENDING: "SUBSCRIPTION_TRIAL_ENDING",
  SUBSCRIPTION_TRIAL_EXPIRED: "SUBSCRIPTION_TRIAL_EXPIRED",
  SUBSCRIPTION_ACTIVATED: "SUBSCRIPTION_ACTIVATED",
  SUBSCRIPTION_RENEWED: "SUBSCRIPTION_RENEWED",
  SUBSCRIPTION_RENEWAL_REMINDER: "SUBSCRIPTION_RENEWAL_REMINDER",
  SUBSCRIPTION_RENEWAL_CANCELLED: "SUBSCRIPTION_RENEWAL_CANCELLED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",

  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  EMAIL_CHANGED: "EMAIL_CHANGED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  LOGIN_DETECTED: "LOGIN_DETECTED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",

  NEW_REVIEW: "NEW_REVIEW",
  NEW_RATING: "NEW_RATING",

  SYSTEM: "SYSTEM",
  PROMOTION: "PROMOTION",
});

const NOTIFICATION_TYPE_VALUES = Object.freeze(
  Object.values(NOTIFICATION_TYPES),
);

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_TYPE_VALUES,
};
